Adding GroupKFold and testing it
hyperopt/hyperopt-sklearn pull request #200
Opened 2023-09-21 05:48 UTC by hyun-seo

Referring to #157, there is an issue about group cross-validation.

This pull request implementation this issue by adding new argument `kfolds_group` and
 using `sklearn.model_selection.GroupKFold`.

2023-10-03 13:19 UTC, mandjevant requested changes
Requesting these initial changes for it to go through the automated testing.
Once it gets through, Ill take a closer look

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/_cost_fn.py
> +             kfolds_group: typing.Union[list, np.ndarray]  = None,
```suggestion
             kfolds_group: typing.Union[list, np.ndarray] = None,
```

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/_cost_fn.py
> +
```suggestion

```

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/_cost_fn.py
> +
Leave newline, remove whitespace.

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/_cost_fn.py
> +
```suggestion

```

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/_cost_fn.py
> +
Leave newline, remove whitespace.

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/estimator.py
> +                     kfolds_group =kfolds_group,
```suggestion
                     kfolds_group = kfolds_group,
```

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/estimator.py
> +
```suggestion

```

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/estimator.py
> +
Leave newline, remove whitespace.

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/estimator.py
> +
```suggestion

```

2023-10-03 13:19 UTC, mandjevant commented on hpsklearn/estimator/estimator.py
> +
Leave newline, remove whitespace.

2023-10-03 13:19 UTC, mandjevant commented on tests/test_estimator/test_estimator.py
> +        cls.fit(X, y, cv_shuffle=True, n_folds=5, kfolds_group=[0]*500 + [1]*500 + [2]*500 + [3]*500 + [4]*500)
```suggestion
        cls.fit(X, y, cv_shuffle=True, n_folds=5, kfolds_group=[0]*500 + [1]*500 + [2]*500 + [3]*500 + [4]*500)  # noqa: E226
```

2023-10-03 13:19 UTC, mandjevant commented on tests/test_estimator/test_estimator.py
```suggestion


```

2023-10-03 13:19 UTC, mandjevant commented on tests/test_estimator/test_estimator.py
```suggestion


```

2023-10-04 19:00 UTC, mandjevant commented on hpsklearn/estimator/estimator.py
> +                     kfolds_group = kfolds_group,
```suggestion
                     kfolds_group=kfolds_group,
```
My bad. My previous review on this line was incorrect.

Saturday it's on my list to properly look at this pr

2023-10-05 07:25 UTC, mandjevant commented on tests/test_estimator/test_estimator.py
> +        cls.fit(X, y, cv_shuffle=True, n_folds=5, kfolds_group=np.array([0]*500 + [1]*500 + [2]*500 + [3]*500))  # noqa: E226
```suggestion
        cls.fit(X, y, cv_shuffle=True, n_folds=5,
                kfolds_group=np.array([0]*500 + [1]*500 + [2]*500 + [3]*500))  # noqa: E226
```

2023-10-06 01:07 UTC, hyun-seo commented
@mandjevant 
Thank you so much for taking the time to review my pr. 
This is my first attempt at contributing to open source and I had a lot of issues, but I think I learned a lot from your kind help.
I have one question: what is the exact meaning of # noqa: E226 in the testcode? Why is this phrase needed in the test?

2023-10-06 08:05 UTC, mandjevant commented
> @mandjevant Thank you so much for taking the time to review my pr. This is my first attempt at contributing to open source and I had a lot of issues, but I think I learned a lot from your kind help. I have one question: what is the exact meaning of # noqa: E226 in the testcode? Why is this phrase needed in the test?

Thank you for your contribution!
The reason your PR did not go through automated testing was because of flake8 style guide enforcement. In most lines, flake was correct and notified us of style issues that we resolved. But in that one line, I deemed that flake8 was wrong. 
It threw an inconsistency with [rule E226](https://www.flake8rules.com/rules/E226.html) which, when enforced, would make the line unreadable.

Thus, I [suppressed the rule](https://flake8.pycqa.org/en/3.1.1/user/ignoring-errors.html) on (only) that line by adding a comment stating `noqa: E226`.

2023-10-08 09:52 UTC, mandjevant requested changes
In addition, please change 
```
n_folds: int, default is None
            When n_folds is not None, use K-fold cross-validation when
            n_folds > 2. Or, use leave-one-out cross-validation when
            n_folds = -1.
```
to 

```
n_folds: int, default is None
            When n_folds is not None, use K-fold cross-validation when
            n_folds > 2. Or, use leave-one-out cross-validation when
            n_folds = -1. For Group K-fold cross-validation, functions as
            `n_splits`.
```

In both places:

https://github.com/hyperopt/hyperopt-sklearn/blob/9938225c7d4dd85fbc45be12aa2f74cdde527ad6/hpsklearn/estimator/estimator.py#L244C30-L244C30

https://github.com/hyun-seo/hyperopt-sklearn/blob/9938225c7d4dd85fbc45be12aa2f74cdde527ad6/hpsklearn/estimator/_cost_fn.py#L60C26-L60C26

Function and test case look appropriate

2023-10-08 09:52 UTC, mandjevant commented on hpsklearn/estimator/estimator.py
> +                equal to the number of samples in X.
```suggestion
                equal to the number of samples in X.

```

2023-10-08 09:52 UTC, mandjevant commented on tests/test_estimator/test_estimator.py
> +    Class for testing estimator with cross validation
```suggestion
    Class for testing estimator with group cross validation
```

2023-10-09 09:33 UTC, mandjevant approved these changes
Looks good! Thanks for your contribution!
@bjkomer Any thoughts?

2023-10-20 10:45 UTC, mandjevant commented
Ill go ahead and merge this. Thank you for your contribution @hyun-seo

2023-10-20 10:45 UTC, merged